import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface PDFExportOptions {
  title: string;
  data: any[];
  columns: { header: string; key: string; width?: number }[];
  filters?: Record<string, any>;
  generatedBy?: string;
}

export async function exportToPDF(options: PDFExportOptions) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  let yPos = 20;

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('RAILWAY POLICE', pageWidth / 2, yPos, { align: 'center' });
  yPos += 10;

  doc.setFontSize(16);
  doc.text(options.title, pageWidth / 2, yPos, { align: 'center' });
  yPos += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(
    `Generated: ${new Date().toLocaleString('en-IN')}`,
    pageWidth - 20,
    yPos,
    { align: 'right' }
  );
  yPos += 5;

  doc.setLineWidth(0.5);
  doc.line(20, yPos, pageWidth - 20, yPos);
  yPos += 10;

  if (options.filters && Object.keys(options.filters).length > 0) {
    doc.setFontSize(10);
    doc.text('Filters Applied:', 20, yPos);
    yPos += 5;
    Object.entries(options.filters).forEach(([key, value]) => {
      if (value) {
        doc.text(`${key}: ${value}`, 25, yPos);
        yPos += 5;
      }
    });
    yPos += 5;
  }

  const tableData = options.data.map((row) =>
    options.columns.map((col) => {
      const keys = col.key.split('.');
      let value: any = row;
      for (const key of keys) {
        value = value?.[key];
      }
      if (value instanceof Date) {
        return value.toLocaleDateString('en-IN');
      }
      return value?.toString() || '';
    })
  );

  autoTable(doc, {
    head: [options.columns.map((col) => col.header)],
    body: tableData,
    startY: yPos,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [29, 78, 216], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    margin: { left: 20, right: 20 },
  });

  const finalY = (doc as any).lastAutoTable.finalY || yPos;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text('Computer generated report', pageWidth / 2, pageHeight - 20, {
    align: 'center',
  });

  if (options.generatedBy) {
    doc.text(`Generated by: ${options.generatedBy}`, pageWidth / 2, pageHeight - 15, {
      align: 'center',
    });
  }

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, pageHeight - 10, {
      align: 'right',
    });
  }

  doc.save(`${options.title.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
}

